/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controller.ControllerMail;
import Controller.ControllerUser;
import Type.TypeMail;
import javax.swing.JOptionPane;

public class FrameSendMail extends javax.swing.JFrame {

    ControllerMail controllerMail = new ControllerMail();
    ControllerUser controllerUser = new ControllerUser();

    /**
     * Creates new form FrameSendMail
     */
    public FrameSendMail() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public FrameSendMail(TypeMail mail) {
        initComponents();
        setLocationRelativeTo(null);

        btnGonder.setVisible(false);
        txtAlan.setEditable(false);
        txtKonu.setEditable(false);
        txtGovde.setEditable(false);
        txtGonderen.setEditable(false);
        txtGonderen.setEnabled(true);

        txtGonderen.setText(mail.getGonderen().getEposta());
        txtAlan.setText(mail.getAlan().getEposta());
        txtKonu.setText(mail.getKonu());
        txtGovde.setText(mail.getGovde());

    }

    public FrameSendMail(String gonderenEposta) {
        initComponents();
        setLocationRelativeTo(null);

        txtGonderen.setText(gonderenEposta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAlan = new javax.swing.JTextField();
        txtKonu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGovde = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGonderen = new javax.swing.JTextField();
        btnGonder = new javax.swing.JButton();
        txtUyarı = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Alıcı");

        txtAlan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlanKeyReleased(evt);
            }
        });

        jLabel2.setText("Konu");

        txtGovde.setColumns(20);
        txtGovde.setRows(5);
        jScrollPane1.setViewportView(txtGovde);

        jLabel3.setText("İçerik");

        jLabel4.setText("Kimden");

        txtGonderen.setEnabled(false);

        btnGonder.setText("GÖNDER");
        btnGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGonderActionPerformed(evt);
            }
        });

        txtUyarı.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUyarı)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAlan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtGonderen, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtKonu, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(20, 20, 20))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGonder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGonderen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUyarı)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGonderActionPerformed

        if (txtAlan.getText().contains("/")) {
            if (controllerMail.Ekle(txtGonderen.getText(), txtAlan.getText().split("/"), txtKonu.getText(), txtGovde.getText())) {
                JOptionPane.showMessageDialog(null, "Gönderildi.");
            } else {
                JOptionPane.showMessageDialog(null, "Gönderilemedi.");
            }
            return;
        }

        TypeMail mail = new TypeMail();
        mail.setGonderen(controllerUser.Getir(txtGonderen.getText()));
        mail.setAlan(controllerUser.Getir(txtAlan.getText()));
        mail.setKonu(txtKonu.getText());
        mail.setGovde(txtGovde.getText());
        if (controllerMail.Ekle(mail)) {
            JOptionPane.showMessageDialog(null, "Gönderildi.");
        } else {
            JOptionPane.showMessageDialog(null, "Gönderilemedi.");
        }
    }//GEN-LAST:event_btnGonderActionPerformed

    public boolean EpostaAdresKontrol() {
        if (txtAlan.getText().contains("/")) {
            String[] alicilar = txtAlan.getText().split("/");
            for (String alici : alicilar) {
                if (controllerUser.Getir(alici) == null) {
                    return false;
                }
            }
        }
        else if (controllerUser.Getir(txtAlan.getText()) == null) {
            return false;
        }
        return true;
    }
    private void txtAlanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlanKeyReleased
        txtUyarı.setText("");
        if (!EpostaAdresKontrol()) {
            txtUyarı.setText("Geçersiz E-posta adresi bulunmakta !");
        }
    }//GEN-LAST:event_txtAlanKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGonder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlan;
    private javax.swing.JTextField txtGonderen;
    private javax.swing.JTextArea txtGovde;
    private javax.swing.JTextField txtKonu;
    private javax.swing.JLabel txtUyarı;
    // End of variables declaration//GEN-END:variables
}
