/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class ArZorlukSecim extends javax.swing.JFrame {

    /**
     * Creates new form ArZorlukSecim
     */
    public ArZorlukSecim() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGezgin = new javax.swing.JButton();
        btnHaci = new javax.swing.JButton();
        btnIzci = new javax.swing.JButton();
        btnSavasci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zorluk Seviyesi");

        btnGezgin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnGezgin.setText("GEZGİN");
        btnGezgin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGezginActionPerformed(evt);
            }
        });

        btnHaci.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnHaci.setText("HACI");
        btnHaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaciActionPerformed(evt);
            }
        });

        btnIzci.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnIzci.setText("İZCİ");
        btnIzci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzciActionPerformed(evt);
            }
        });

        btnSavasci.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSavasci.setText("SAVAŞÇI");
        btnSavasci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavasciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("ZORLUK SEVİYESİNİ SEÇİNİZ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSavasci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnHaci, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnGezgin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnIzci, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHaci)
                    .addComponent(btnGezgin)
                    .addComponent(btnIzci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSavasci)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaciActionPerformed
         new ArOyun(9).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnHaciActionPerformed

    private void btnGezginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGezginActionPerformed
         new ArOyun(7).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnGezginActionPerformed

    private void btnIzciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzciActionPerformed
         new ArOyun(5).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnIzciActionPerformed

    private void btnSavasciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavasciActionPerformed
        new ArOyun(3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSavasciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGezgin;
    private javax.swing.JButton btnHaci;
    private javax.swing.JButton btnIzci;
    private javax.swing.JButton btnSavasci;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
