package Test;

import Core.ObjectHelper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CreateDataBase extends ObjectHelper {

    public boolean Create() {
        try {
            try {
                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateDataBase.class.getName()).log(Level.SEVERE, null, ex);
            }
            Connection connection = DriverManager.getConnection(getDatabase() + ";create=true");

            //bolum
            connection.createStatement().execute("Create Table bolum ("
                    + "id int generated by default as identity (START WITH 2, INCREMENT BY 1),"
                    + "ad varchar(50),"
                    + "dersProgrami_id int,"
                    + "sure int)"
            );
            connection.createStatement().execute("Insert Into bolum "
                    + "values(DEFAULT,'Bilgisayar Muhendisligi',1,4)"
            );

            //ders
            connection.createStatement().execute("Create Table ders ("
                    + "id int generated by default as identity (START WITH 2, INCREMENT BY 1),"
                    + "ad varchar(50),"
                    + "kredi int)"
            );
            connection.createStatement().execute("Insert Into ders "
                    + "values(DEFAULT,'Java Programlama',4)"
            );

            //ders rogrami
            connection.createStatement().execute("Create Table ders_programi ("
                    + "id int generated by default as identity (START WITH 2, INCREMENT BY 1),"
                    + "ad varchar(50),"
                    + "pazartesi int,"
                    + "sali int,"
                    + "carsamba int,"
                    + "persembe int,"
                    + "cuma int)"
            );
            connection.createStatement().execute("Insert Into ders_programi "
                    + "values(DEFAULT,'BILMUH Ders Programi',1,1,1,1,1)"
            );

            //idari memur
            connection.createStatement().execute("Create Table idari_memur ("
                    + "id int generated by default as identity (START WITH 2, INCREMENT BY 1),"
                    + "tcno varchar(50),"
                    + "ad varchar(50),"
                    + "soyad varchar(50),"
                    + "yas int,"
                    + "gorev varchar(50))"
            );
            connection.createStatement().execute("Insert Into idari_memur "
                    + "values(DEFAULT,'12345678910','hakan','tas',54,'rektor')"
            );
            
            //notlar
            connection.createStatement().execute("Create Table notlar ("
                    + "id int generated by default as identity (START WITH 2, INCREMENT BY 1),"
                    + "ogrenci_id int,"
                    + "ders_id int,"
                    + "puan int)"
            );
            connection.createStatement().execute("Insert Into notlar "
                    + "values(DEFAULT,1,1,65)"
            );
              //ogretim uyesi
            connection.createStatement().execute("Create Table ogretimuye ("
                    + "id int generated by default as identity (START WITH 2, INCREMENT BY 1),"
                    + "tcno varchar(50),"
                    + "ad varchar(50),"
                    + "soyad varchar(50),"
                    + "yas int,"
                    + "bolum_id int)"
            );
            connection.createStatement().execute("Insert Into ogretimuye "
                    + "values(DEFAULT,'12345678910','ertugrul','arik',42,1)"
            );

             //ogrenci
            connection.createStatement().execute("Create Table ogrenci ("
                    + "id int generated by default as identity (START WITH 2, INCREMENT BY 1),"
                    + "tcno varchar(50),"
                    + "ad varchar(50),"
                    + "soyad varchar(50),"
                    + "yas int,"
                    + "baba_adi varchar(50),"
                    + "ana_adi varchar(50),"
                    + "uyruk varchar(50),"
                    + "bolum_id int)"
            );
            connection.createStatement().execute("Insert Into ogrenci "
                    + "values(DEFAULT,'12345678910','ahmet','balaban',19,'mustafa','fadime','turkiye',1)"
            );
            
           
            return true;
        } catch (SQLException ex) {
            Logger.getLogger(CreateDataBase.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

}
